datastax/release-notes

OpsCenter_6.8_Release_Notes.md
=> Added release dates

DSE_6.8_Release_Notes.md
=> Adjust formatting

DSE_5.1_Release_Notes.md, DSE_6.0_Release_Notes.md, DSE_6.7_Release_Notes.md, DSE_6.8_Release_Notes.md
Updated compatibility for DSE 6.7, 6.0 & 5.1
=> Updated compatibility for DSE 6.7, 6.0 & 5.1

DSE_6.8_Release_Notes.md
=> minor formatting change

DSE_5.1_Release_Notes.md, DSE_6.0_Release_Notes.md, DSE_6.7_Release_Notes.md, DSE_6.8_Release_Notes.md, OpsCenter_6.8_Release_Notes.md
=> Documentation updates

DSE_5.1_Release_Notes.md
Fixed minor formatting and verbiage
=> Fixed minor formatting and verbiage

DSE_6.8_Release_Notes.md
Missing DB-4934 from the DSE 6.8.11 release
=> Added missing DB-4934 entry

Luna_Streaming_2.7_Release_Notes.md
Also add link to Apache Pulsar 2.7.2 release notes.
=> Add upgrade considerations

Luna_Streaming_2.7_Release_Notes.md
Add release notes for recent Luna Streaming releases:
- 2.7.2.1.0.1
- 2.7.2.1.1.0
=> Add release notes for Luna Streaming 2.7.2.1.0.1 and 2.7.2.1.1.0

Luna_Streaming_2.8_ReleaseNotes.md
=> Fix typo in Luna_Streaming_2.8_ReleaseNotes.md

DataStax_Studio_6.8_Release_Notes.md
Release notes for Studio 6.8.15
https://datastax.jira.com/projects/STUDIO/versions/31168/tab/release-report-all-issues
=> Add Studio 6.8.15 release notes

DSE_5.1_Release_Notes.md
Adds 5.1.27 release notes.
Additionally fixes components versions for 5.1.26
=> Add 5.1.27 release notes

Luna_Streaming_2.7_Release_Notes.md
I also add rn for 1.1.13 and 1.1.12 since they were missing
=> Luna Streaming 2.7.2.1.1.14 and 2.7.2.1.1.15

DataStax_Studio_6.8_Release_Notes.md
List of jira issues fixed in Studio 6.8.17 is
https://datastax.jira.com/issues/?jql=project%20%3D%20%22STUDIO%22%20AND%20fixVersion%20%3D%20%226.8.17%22
=> Studio 6.8.17 release notes

DSE_5.1_Release_Notes.md
=> DSE 5.1.28 Release Notes

DSE_6.8_Release_Notes.md
=> DSE 6.8.19 Release Notes

3rd-party-software/DSE_6.8.21_3rd_party_software.md, DSE_6.8_Release_Notes.md
=> DSE 6.8.21 Release Notes

3rd-party-software/DSE_5.1.30_3rd_party_software.md, DSE_5.1_Release_Notes.md
=> DSE 5.1.30 Release Notes

Luna_Streaming_2.8.3_Release_Notes.md
* Copied from LS280
* Did a diff starting from Apache branch 2.8
* Removed build and tests stuff
=> Luna streaming: first release of LS 283 (WIP - DO NOT MERGE)

Luna_Streaming_2.8.3_Release_Notes.md
@nicoloboschi just some small changes.
=> small-changes

3rd-party-software/DSE_6.8.22_3rd_party_software.md, DSE_6.8_Release_Notes.md
=> DSE 6.8.22 Release Notes

3rd-party-software/DSE_6.8.23_3rd_party_software.md, DSE_6.8_Release_Notes.md
Update DSE 6.8 release notes
Add DSE 6.8.23 3rd party software list
=> DSE 6.8.23 Release Notes

Luna_Streaming_2.7_Release_Notes.md
Updated notes for 2.7.2 1.1.36
=> Release notes update (security -> stability)

3rd-party-software/DSE_6.8.24_3rd_party_software.md, DSE_6.8_Release_Notes.md
Adds DSE 6.8.24 Release Notes and 3rd-party software list.
=> DSE 6.8.24 Release Notes

DSE_6.7_Release_Notes.md, DSE_6.8_Release_Notes.md
Added verbiage to notify change in SSTable format and/or version.
=> Added verbiage to notify change in SSTable format and/or version

DSE_5.1_Release_Notes.md, DSE_6.8_Release_Notes.md
* Release notes for DSE 6.8.26
* Release notes for DSE 5.1.33
=> Release notes for September 12 2022 DSE releases (5.1.33 and 6.8.26)

3rd-party-software/DSE_6.8.27_3rd_party_software.md, DSE_6.8_Release_Notes.md
=> DSE 6.8.27

3rd-party-software/DSE_6.8.28_3rd_party_software.md, DSE_6.8_Release_Notes.md
=> DSE 6.8.28 release notes

3rd-party-software/DSE_6.8.32_3rd_party_software.md, 3rd-party-software/DSE_6.8.33_3rd_party_software.md
Removes known test dependencies.
=> Further fixes DSE 6.8.32 and 6.8.33 3rd-party dependencies

DSE_6.8_Release_Notes.md
Added Rocky Linux 8 support in 6.8.33 release notes
=> Added Rocky Linux 8 support in 6.8.33 release notes

3rd-party-software/DSE_5.1.37_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.37 Release

3rd-party-software/DSE_6.8.34_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.34 Release

DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Add DSP-23170 with Rocky 8 support.

3rd-party-software/DSE_6.8.37_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.37 release notes

3rd-party-software/DSE_5.1.39_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.39 release notes

DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Add DSP-23229 to DSE_6.8_Release_Notes.md

DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Add DSP-23444 (RHEL9) to DSE_5.1_Release_Notes.md

DataStax_Studio_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Studio 6.8.32 Release notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.27 Release Notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.28 Release Notes

3rd-party-software/DSE_5.1.40_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.40 release notes

3rd-party-software/DSE_6.8.39_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.39 release notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OPSC-17381 OpsCenter 6.8.29 release notes

3rd-party-software/DSE_6.8.40_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.40 release notes

3rd-party-software/DSE_5.1.41_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.41 release notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.30 Release

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.31 Release

3rd-party-software/DSE_6.8.41_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.41 release notes

3rd-party-software/DSE_5.1.42_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.42 release notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.33 Release

3rd-party-software/DSE_5.1.43_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.43 Release Notes

3rd-party-software/DSE_6.8.43_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.43 Release Notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.36 Release

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.38 Release

3rd-party-software/DSE_6.8.50_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.50 release notes

3rd-party-software/DSE_6.9.0_3rd_party_software.md, DSE_6.9_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.9.0 release notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.39 Release

3rd-party-software/DSE_6.9.2_3rd_party_software.md, DSE_6.9_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.9.2 release notes

3rd-party-software/DSE_5.1.46_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.46 Release Notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.40 Release

3rd-party-software/DSE_6.9.3_3rd_party_software.md, DSE_6.9_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.9.3 Release Notes

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Luna Streaming 3.1.4.9

3rd-party-software/DSE_6.8.52_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.52 Release Notes

3rd-party-software/DSE_6.9.4_3rd_party_software.md, DSE_6.9_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.9.4 Release Notes

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Luna Streaming 3.1.4.10

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.41 Release

3rd-party-software/DSE_6.9.5_3rd_party_software.md, DSE_6.9_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.9.5 Release Notes

3rd-party-software/DSE_5.1.47_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.47 Release Notes

3rd-party-software/DSE_6.8.53_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.53 Release Notes

3rd-party-software/DSE_6.8.54_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.54 Release Notes

3rd-party-software/DSE_6.9.7_3rd_party_software.md, DSE_6.9_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.9.7 Release Notes

3rd-party-software/DSE_5.1.48_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.48 Release Notes

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Luna Streaming 3.1.4.13

3rd-party-software/DSE_6.8.55_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.55 Release Notes

3rd-party-software/DSE_6.8.56_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.56 Release Notes

3rd-party-software/DSE_6.8.57_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.57 Release Notes

3rd-party-software/DSE_6.9.13_3rd_party_software.md, DSE_6.9_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.9.13 Release Notes

3rd-party-software/DSE_6.9.14_3rd_party_software.md, DSE_6.9_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.9.14 Release Notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter-6.8.46 Release Notes
