datastax/release-notes

DSE_5.1_Release_Notes.md
- DB-4884 was fixed in 5.1.21
- DSP-21394, DSP-21674, DB-4806 were not included in release
=> Correct release notes

DSE_6.8_Release_Notes.md
Jira issue numbers are not publicly available however they are shared with
customers and used to track the progress of work and hence they should be part
of the release notes.
=> Adds jira issue number which are shared to customers

DSE_6.8_Release_Notes.md
In addition, I have verified that https://docs.datastax.com/en/home/docs/3rdpartysoftware/dse6830.html does not list excluded `nekothml` so we don't need to update third-party components list.
=> Add missing information about DSP-22902 in 6.8.30 release notes

.github/pull_request_template.md, .github/workflows/release-auto-tag.yaml
See commits for more info.
Tested using https://github.com/riptano/test-shared-github-actions
* Success: [run #4089162502](https://github.com/riptano/test-shared-github-actions/actions/runs/4089162502) GitHub action succeeded creating tag
* Ignore: [run #4089048348](https://github.com/riptano/test-shared-github-actions/actions/runs/4089048348) GitHub Action skipped because title didn't match expected pattern
* Failure: [run #4089174098](https://github.com/riptano/test-shared-github-actions/actions/runs/4089174098) GitHub Action failed because tag already existed
=> DSP-23094 Automatically creates a product version tag when merging PR with new release changes

3rd-party-software/DSE_6.8.32_3rd_party_software.md
Removes test-only dependencies that are not shipped with DSE and that report LGPL which might raise unnecessary concerns. In cases of dependencies with multiple licenses and we know which one we're using, report only the licenses in use.
=> Fixes DSE 6.8.32 3rd-party dependencies

3rd-party-software/DSE_6.8.32_3rd_party_software.md
Further removes test-only dependencies that are not shipped with DSE. Further cleans up cases with multiple licenses after validation with DataStax legal.
In cases we report multiple versions having different versions we report individual licenses per version.
Adds note about licenses in use.
=> Further fixes DSE 6.8.32 3rd-party dependencies

DSE_6.8_Release_Notes.md
Add missing support for Rocky Linux 9 and fix markdown format.
=> Fix DSE 6.8.33 Release Notes

3rd-party-software/DSE_6.8.32_3rd_party_software.md, 3rd-party-software/DSE_6.8.33_3rd_party_software.md
Updated `release-notes-generator` to handle scenario that the same dependency and version is reported multiple times which would cause duplicate licenses being reported.
=> Further fixes DSE 6.8.32 and 6.8.33 3rd-party dependencies

3rd-party-software/DSE_5.1.38_3rd_party_software.md, DSE_5.1_Release_Notes.md
DSE 5.1.38 release notes and 3rd-party listing
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.38 release notes

3rd-party-software/DSE_6.8.36_3rd_party_software.md, DSE_6.8_Release_Notes.md
DSE 6.8.36 release notes and 3rd-party listing.
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.36 release notes

DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Update DSE_6.8_Release_Notes.md - fix typo CVE

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OPSC-17353 Fixed broken SAI monitoring link in 6.8.27 release

OpsCenter_6.8_Release_Notes.md
Fix missing Jira issue in OpsCenter 6.8.27 release.
=> Fix missing Jira issue in OpsCenter 6.8.27 release

DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Amended a wrong jackson-databind version reported in DSP-23613

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.32 Release

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Adds warning about storage cluster regression introduced in 6.8.33

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.35 Release

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> addressed PR comments for OpsCenter 6.8.35 Release

3rd-party-software/DSE_6.8.44_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.44 release notes

3rd-party-software/DSE_6.8.45_3rd_party_software.md, 3rd-party-software/DSE_6.8.46_3rd_party_software.md, DSE_6.8_Release_Notes.md
Supersedes https://github.com/datastax/release-notes/pull/139
Provides release notes for DSE `6.8.46` and internal DSE release `6.8.45` (identical to `6.8.46`).
=> DSE 6.8.46 release notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.37 Release

3rd-party-software/DSE_6.8.49_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.49 Release Notes

3rd-party-software/DSE_5.1.45_3rd_party_software.md, DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.45 release notes

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Added Release Note for Luna Streaming 3.1.4.6

DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Fix DSE 6.8.51 Release Notes

Luna_Streaming_2.10_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 2.10.6.0 Release

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 3.1.4.7 Release

Luna_Streaming_2.10_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 2.10.6.1 Release

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 3.1.4.8 Release

Luna_Streaming_2.10_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 2.10.6.2 Release

DSE_6.8_Release_Notes.md
This commit amends the release note of DSP-23187 by adding the remark about the order of polygon points in the JSON representation.
----
* DSE
* OpsCenter
* Studio
=> Update DSP-23187 release note

DSE_6.8_Release_Notes.md
Adds missing DSP-24437 which was wrongly set with fix version set to 6.8.52 instead of 6.8.53 where it was merged.
----
* DSE
* OpsCenter
* Studio
=> Fixes DSE 6.8.53 Release Notes

DSE_5.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Adds DSE Platform updates with support for al2023

Luna_Streaming_2.10_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 2.10.6.3 Release

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 3.1.4.12 Release

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.42 Release

DSE_6.9_Release_Notes.md
Adding caution text to help customers understand the full upgrade procedure when they configure transitional mode for node-to-node encryption, as seen in the Support & Documentation ticket https://datastax.jira.com/browse/DOC-5077.
----
* DSE
* OpsCenter
* Studio
=> Add Support/Customer-requested information for transitional mode in the DSE_6.9_Release_Notes.md 

DSE_5.1_Release_Notes.md
DSE 5.1.48 Release Notes amended release date
----
* DSE
* OpsCenter
* Studio
=> DSE 5.1.48 Release Notes amended release date

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OpsCenter 6.8.43 Release

DSE_6.9_Release_Notes.md
Per the request in https://datastax.jira.com/browse/DSP-24766, this PR adds the required minimum JDK (11.0.19) and Python (3.8 - 3.11) versions required to run DSE 6.9.
----
* DSE
* OpsCenter
* Studio
=> DSP-24766-69: Update the DSE_6.9_Release_Notes.md with the minimum JDK and Python versions

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 3.1.4.14 Release

Luna_Streaming_4.0_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 4.0.3.2 Release

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Added missing release note for OPSC-17614

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OPSC-17698 OpsCenter 6.8.44 Release

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 3.1.4.15 Release 

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 3.1.4.16 Release

3rd-party-software/DSE_6.8.58_3rd_party_software.md, DSE_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.8.58 Release Notes

DSE_6.9_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> DSE 6.9.10 Release Notes

OpsCenter_6.8_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> OPSC-17715 OpsCenter 6.8.45 Release

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Luna Streaming 3.1.4.17

Luna_Streaming_4.0_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Luna Streaming 4.0.3.4

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Luna Streaming 3.1.4.18

Luna_Streaming_3.1_Release_Notes.md
----
* DSE
* OpsCenter
* Studio
=> Lunastreaming 3.1.4.19 Release
